### ISSUE TITLE
Champs "Date" des offres

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#1]
Salut Pierre,
Dans les offres côté public, le champs "date" (correspondant aux dates de vente et de validité) apparait même lorsqu'il n'y'a rien de spécifié dans les champs. Possible de le faire disparaitre?

![image](https://cloud.githubusercontent.com/assets/10245123/5577815/cb4cd258-9019-11e4-8f66-a6828a203a73.png)

Lien :
http://www.simply-ce.com/demo/billetterie/offre/36566-x-pathe-gaumont-national

**Comment by sylfabre** [comment]
@remijean Rappel

**Comment by remijean** [comment]
@simplyce Corrigé en attente de mise en production
