### ISSUE TITLE
Problème interface Subventions sur justificatif / Compta

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#11]
Bonjour,

Problème assez critique, on valide de nombreuses subventions sur justificatifs et nous ne notons aucun déversement en compta (ni dans les dettes à payer, ni dans la recherche d'écritures comptables).  

http://www.simply-ce.com/demo-vp/subventions/justificatifs/valides/8709 

Merci.

**Comment by ArnaudDLT** [comment]
@simplyce il n'y a pas de compte en banque paramétré pour ce site, ce qui explique le problème que vous rencontrez
