### ISSUE TITLE
Page de garde des offres de billetterie

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#13]
Suite à plusieurs retours client, serait-il possible d'enlever de ma plateforme la page de garde des offres. Ils sont troublés par le fait qu'aucun lien ne soit rattaché aux icones, et remontent des bugs aux élus de CE qui aimeraient par conséquent voir disparaitre cette page de garde.

Merci

**Comment by sylfabre** [comment]
@simplyce Quelle url stp ?

**Comment by simplyce** [comment]
http://www.simply-ce.com/demo/page/7220-offres

**Comment by sylfabre** [comment]
@simplyce Merci
