### ISSUE TITLE
Affichage du montant de la subvention à la place du prix de vente

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#14]
Lorsqu'une subvention est mise en place sur des offres du catalogue, et qu'on clique sur "j'achète" d'une offre subventionnées, on tombe sur le détail de l'offre. Dans ce dernier, le montant subventionné est affiché sous le champs prix de vente (cf ci dessous). 

![image](https://cloud.githubusercontent.com/assets/10245123/6394988/aa7ad928-bdd5-11e4-8c76-668525683863.png)

http://www.simply-ce.com/demomismo/billetterie/offre/36889-p-ugc-national

**Comment by remijean** [comment]
Bug corrigé
