### ISSUE TITLE
Urgent : Admin inaccessible

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#15]
Bonjour,

Suite à l'activation de certaines apps et à l'enregistrement, le côté "admin" de la plateforme devient inaccessible pour moi. Ci-dessous la page sur laquelle je tombe lorsque je clique sur l'admin:

![image](https://cloud.githubusercontent.com/assets/10245123/6488556/945fe0bc-c298-11e4-84d8-e57530cd56b4.png)

http://www.cennd.fr/admin/liste

**Comment by sylfabre** [comment]
@simplyce Je regarde. N'hésite pas à m'appeler au 07 60 40 41 28 en cas de problème urgent !

**Comment by sylfabre** [comment]
@simplyce C'est corrigé
