### ISSUE TITLE
Non prise en compte des subventions lors d'inscription manuelle

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#16]
On crée une offre "X" dans les "ventes en ligne".

On ajoute une subvention sur l'offre "X" seulement.

Lors de l'achat en ligne par le salarié, la subvention fonctionne bien. Par contre lors d'une inscription côté admin par l'élu (dans gérer l'offre/Inscrits), la subvention ne s'applique pas.

Est-ce normal? Y'a-t-il une manip qui m'aurait échappé?

**Comment by sylfabre** [comment]
@simplyce As-tu un exemple concret sous la main stp ?

**Comment by simplyce** [comment]
Après plusieurs manip, j'ai réussi à faire ce que je voulais !

Dsl pour le dérangement.
