### ISSUE TITLE
Disparition d'icônes (menus)

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#17]
Bonjour 

Sur toutes mes plateformes (et celles de mes clients), les icônes liées aux offres, aux sondages et aux remboursements ont curieusement et soudainement disparu. 

![image](https://cloud.githubusercontent.com/assets/10245123/6559472/79bf1a9a-c683-11e4-85db-0bce7dc508e7.png)

**Comment by sylfabre** [comment]
@simplyce Je regarde tout de suite

**Comment by sylfabre** [comment]
@simplyce Le problème est résolu temporairement, je vais prendre contact avec notre hébergeur car le serveur envoie une image qui n'est pas complète (c'est pour ça que certaines icônes s'affichent mais pas toutes). Le problème ne semble pas venir directement de notre site mais j'aimerais savoir pourquoi il se produit pour éviter qu'il ne revienne

**Comment by sylfabre** [comment]
@simplyce J'ai enfin une piste pour expliquer le bug. Je le ferme ici, il est noté dans notre outil de suivi en interne
