### ISSUE TITLE
Urgent : Admin master / modules ventes

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#18]
Bonjour,

J'ai un souci depuis plusieurs jours avec l'admin master / page ventes. Lorsque j'essaye de charger les ventes sur une période, le chargement tourne sans arrêt et n'affiche rien.

Assez urgent, merci !

![image](https://cloud.githubusercontent.com/assets/10245123/6726202/f36ce208-ce14-11e4-9b2b-70a3f4ad8f3f.png)
http://www.simply-ce.com/demo/master/ventes

**Comment by sylfabre** [comment]
@simplyce On regarde

**Comment by sylfabre** [comment]
@simplyce Le bug est corrigé, on met à jour sur le serveur dans 2 minutes
