### ISSUE TITLE
Subventions sur catalogue / Offre en particulier

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#19]
Dans les subventions, lorsqu'on sélectionne "offres du catalogue" et "offres en particulier", on recherche une offre et les résultats font apparaître l'ensemble des offres du catalogue, même les offres en statut "archivées" ou "ventes suspendues". Il est important pour nous de limiter cela aux ventes en ligne.

![image](https://cloud.githubusercontent.com/assets/10245123/6919279/17591cae-d7b6-11e4-9e7f-5ffa0f5d964e.png)
http://www.simply-ce.com/demo-proservia/subventions/edition?vendorId=8471

**Comment by sylfabre** [comment]
@simplyce Bug bien reçu. Mais je ne peux pas le corriger tout de suite, je suis à l'hôpital pour l'appendicite (tout s'est bien passé), je te fais ça dès que je sors !

**Comment by sylfabre** [comment]
@simplyce Le bug est corrigé mais il faut attendre la prochaine mise en prod pour le voir !
