### ISSUE TITLE
Frais de Livraison par plateforme

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#2]
Salut,

J'ai fait des tests concernant les frais de livraison par plateforme, malheureusement non concluants.
Je veux supprimer les frais de livraison d'une plateforme, mais laisser le choix d'une livraison au CE ou  au domicile du salarié.
![image](https://cloud.githubusercontent.com/assets/10245123/5648374/56f0f328-968e-11e4-87ac-82216c8f7414.png)
http://www.simply-ce.com/demo-proservia/billetterie/liste/produits-livraison/2576 

Les modifications, bien que sauvegardées, ne sont pas appliquées dans le catalogue. A l'achat d'une offre quelconque, voici les choix proposés:
![image](https://cloud.githubusercontent.com/assets/10245123/5648409/998ffb20-968e-11e4-8a40-11f280522d65.png)
http://www.simply-ce.com/demo-proservia/billetterie/livraison/175872-tr0iog66yydtx9oybz48

Merci d'avance !

Malek

**Comment by sylfabre** [comment]
@simplyce Bonjour Malek,

Pour moi ce n'est pas un bug. Sur l'édition de l'offre associée (http://www.simply-ce.com/demo-proservia/billetterie/edition-produit/36566) on voit qu'il y a des frais spécifiques renseignés : ils sont donc prioritaires sur le réglage au niveau de la plateforme.
