### ISSUE TITLE
Emission de billets électroniques

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#20]
Les billets électroniques émis portent vos logos et marques.
![image](https://cloud.githubusercontent.com/assets/10245123/7046622/6c99a0d8-de07-11e4-8660-93d191e22e4a.png)

http://www.simply-ce.com/demo/billetterie/billet/304018-874557b83252b8264cbf774c10800f83534eeeda 

Il faudrait si possible le remplacer par ce fichier. 
![logo-simplyce- -slogan](https://cloud.githubusercontent.com/assets/10245123/7046919/5363e0c2-de09-11e4-925f-71f7531ff3b1.png)

Merci d'avance !

**Comment by sylfabre** [comment]
@simplyce Message reçu, on corrige ça rapidement

**Comment by sylfabre** [comment]
@simplyce J'ai mis ton logo sur les billets, je mets quelle url pour le message à droite ?
