### ISSUE TITLE
Conditions générales de vente

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#21]
![image](https://cloud.githubusercontent.com/assets/10245123/7046964/a0fad1ce-de09-11e4-882b-5e2e22184a8f.png)

Il faudrait remplacer par:
"...au capital de 3000 euros, dont le siège social est situé au 12 rue olivier 44100 NANTES, immatriculée au RCS de Nantes sous le numéro 803 019 769."

Merci

**Comment by sylfabre** [comment]
@simplyce Pourrais-tu nous indiquer l'url de la page en question stp ?
@remijean Peux-tu t'en occuper stp ?

**Comment by remijean** [comment]
@sylfabre 

http://www.simply-ce.com/demo/conditions/cguv
Les options notice.XXX dans simply-ce-.com > inc.config.COMMON.php ne sont pas prises en compte

**Comment by simplyce** [comment]
Ci-dessous l'url...

http://www.simply-ce.com/demo/conditions/cguv

**Comment by sylfabre** [comment]
@simplyce C'est corrigé
