### ISSUE TITLE
Problème "a payé" évènements du CE

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#22]
Malgré la validation du paiement en compta, le paiement s'affiche toujours comme non payé dans la gestion de l'évènement.

![image](https://cloud.githubusercontent.com/assets/10245123/7089773/8bed0392-df9e-11e4-9534-955d4b6fd27c.png)
http://www.simply-ce.com/demo-formationzn31/billetterie/participants/44255

**Comment by sylfabre** [comment]
@ArnaudDLT Relance

**Comment by ArnaudDLT** [comment]
@sylfabre en fait ce bug n'est plus d'actualité depuis longtemps, je le ferme
