### ISSUE TITLE
"Do it yourself" ne fonctionne plus

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#23]
Bonjour,

Lorsque j'essaye d'ajouter un bloc type "video" ou "texte", le système ne réagit pas et ne permet pas de modifier des pages.

![image](https://cloud.githubusercontent.com/assets/10245123/7254647/bcdc503a-e844-11e4-8a55-29bc5458edd9.png)

http://www.simply-ce.com/demo/page/edition/2593

**Comment by sylfabre** [comment]
@simplyce Je regarde immédiatement

**Comment by sylfabre** [comment]
@simplyce Ca devrait être corrigé, je fais quelques tests
