### ISSUE TITLE
Icônes Admin CE et Admin Master ont disparu 

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#24]
Bonjour,
Les icônes des menus admins CE et master ont disparu.

![image](https://cloud.githubusercontent.com/assets/10245123/7271373/3da10e88-e8e3-11e4-86cb-365829df92c1.png)
http://www.simply-ce.com/demo/admin/8057

**Comment by sylfabre** [comment]
@simplyce Yes nous avons vu, nous sommes en train de chercher la cause

**Comment by sylfabre** [comment]
@simplyce Le problème semble être corrigé, il était dû à une différence de configuration entre le serveur et mon ordinateur, ce qui fait que je n'avais pas le bug sur mon ordi et n'ai donc pas pu l'anticiper
