### ISSUE TITLE
Problème Accès

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#25]
Problème d'accès au détail des transactions, lorsque je clique sur l'oeil le système me dit que je n'ai pas les droits d'accès. Or j'en ai besoin pour annuler une commande. 
![image](https://cloud.githubusercontent.com/assets/10245123/7393236/ec9fb9ee-ee8c-11e4-9675-ba20e95584b6.png)

http://www.cetibcotelecoms.fr/membres/achats/133453?admin=true

**Comment by sylfabre** [comment]
@simplyce Corrigé en prod
