### ISSUE TITLE
Champ "Recherche" sur les ventes de produits

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#26]
Lorsqu'on entre plus de 10 références dans une vente de produits, un champs "Recherche" apparaissait pour éviter la multiplication de références illisibles comme ci-dessous

![image](https://cloud.githubusercontent.com/assets/10245123/7393345/76e85200-ee8d-11e4-8d6f-634b7d035417.png)

http://www.cetibcotelecoms.fr/billetterie/offre/45456-i-vente-groupee-de-parfums

**Comment by sylfabre** [comment]
@simplyce En fait la recherche apparaît à l'étape suivante de l'achat.
@ArnaudDLT Qu'en penses-tu ?

**Comment by sylfabre** [comment]
@ArnaudDLT Relance

**Comment by ArnaudDLT** [comment]
@sylfabre @simplyce ce n'est pas un bug, je le place dans la boite à idées
