### ISSUE TITLE
Catalogue : Toutes les catégories ne s'affichent pas

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#28]
Les catégories "Produits" et "Offres du CE" ne s'affichent pas alors qu'il y'a des offres dedans.
![image](https://cloud.githubusercontent.com/assets/10245123/7394027/6d9375b4-ee91-11e4-84f9-7a6a2c6c76f5.png)
http://www.ce-asc.fr/page/7376-offres

**Comment by sylfabre** [comment]
@simplyce Corrigé

**Comment by simplyce** [comment]
Le problème est revenu : Les catégories "Produits" et "Offres du CE" ne s'affichent pas alors qu'il y'a des offres dedans.

**Comment by sylfabre** [comment]
@simplyce Je regarde
