### ISSUE TITLE
Icones apparaissent partout dans l'admin master

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#29]
Sur tous les menus de l'admin master, au niveau des champs de dates, plein d'icones sont apparus
![image](https://cloud.githubusercontent.com/assets/10245123/7409767/86da7426-ef29-11e4-9511-b2de5963ecb3.png)
http://www.simply-ce.com/demo/master/ventes

**Comment by sylfabre** [comment]
@simplyce Bonjour Malek, nous avons identifié le problème, nous sommes e' train de chercher une solution. En fait nous avons travaillé à compresser les images du site pour accélérer le chargement des pages mais ça a quelques effets inattendus sur les formulaires

**Comment by simplyce** [comment]
Ok bien noté, c'est bizarre ça n’apparaît vraiment que sur les champs "date" de tous les formulaires

**Comment by remijean** [comment]
Bug corrigé
