### ISSUE TITLE
Problème Accès offres Admin Master

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#3]
Hello,

Lorsque j'essaye d'accéder à l'édition de n'importe quelle offre depuis l'admin master, j'ai un message d'erreur : 
![image](https://cloud.githubusercontent.com/assets/10245123/5665977/aa7a20a4-975c-11e4-913c-55fffdd23d3a.png)
http://www.simply-ce.com/demo/public/common/static/500.php?uid=54aeb1270afda&mail=sav@simply-ce.com

**Comment by sylfabre** [comment]
@simplyce Corrigé
