### ISSUE TITLE
Urgent : Excel Export des commandes

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#30]
Bonjour,

J'ai un problème à l'ouverture de l'export des commandes excel. Un message d'erreur s'affiche.
![image](https://cloud.githubusercontent.com/assets/10245123/7492852/44982252-f3fc-11e4-9cec-20cacea2d225.png)
http://www.simply-ce.com/demo/master/ventes

**Comment by sylfabre** [comment]
@simplyce Je regarde

**Comment by sylfabre** [comment]
@simplyce  La version 97 - 2003 fonctionne apparemment, je vais voir pour l'autre

**Comment by sylfabre** [comment]
@simplyce C'est corrigé
