### ISSUE TITLE
Bouton "éxécuter le virement" ne fonctionne pas

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#31]
Bonjour,
Dans l'onglet compte de cantonnement, je ne peux pas créditer mon compte bancaire à partir du wallet
![image](https://cloud.githubusercontent.com/assets/10245123/7655963/a32dcf60-fb27-11e4-9eef-962b72e8fc12.png)
http://www.simply-ce.com/demo/master/compte

**Comment by sylfabre** [comment]
@simplyce Hello, je suis en weekend à Rome, je regarde ça à mon retour.
@ArnaudDLT Je ne vois pas ce qui coince d'ici, peux-tu me mettre le message rouge stp ?

**Comment by simplyce** [comment]
Quel message rouge?

**Comment by sylfabre** [comment]
@simplyce Le message s'adressait à Arnaud.
Je viens de corriger le bug et j'ai fait un transfert de 1500€ environ
