### ISSUE TITLE
Admin Master / Transactions

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#32]
Dans le détail des transactions, le CE de l'acheteur et les modalités de livraison, qui étaient présents, ont disparu. Est-ce possible de les remettre svp?

![image](https://cloud.githubusercontent.com/assets/10245123/7771038/a9c9baa6-0094-11e5-8168-c5032fc2da4e.png)
http://www.ceaviapartnernantes.fr/master/ventes/transaction/203686

**Comment by simplyce** [comment]
URGENT : Le CE de l'acheteur et les modalités de livraison ont également disparu dans l'excel, c'est très problématique pour traiter les commandes. Merci de votre réactivité

**Comment by sylfabre** [comment]
@remijean as-tu vu que tu es assigné ?

**Comment by remijean** [comment]
@sylfabre enregistrement des options de livraison

**Comment by sylfabre** [comment]
@simplyce hello Malek, on a eu un bug qui faisait que le site ne demandait pas les informations de livraison dans certains cas. Le bug est corrigé.
Pour rattraper le tir pour les commandes déjà passées, on peut t'aider à contacter les utilisateurs si tu le souhaites pour récupérer les informations manquantes.

**Comment by remijean** [comment]
@simplyce de mon côté j'ai remis le nom du ce
