### ISSUE TITLE
Problème d'ergonomie assez gênant sur la billetterie

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#33]
Sur les écrans de pc carré ou les mobiles, nous avons un problème d'ergonomie sur la billetterie. Le bandeau de gauche affichant les catégories passe par dessus les offres au lieu de bien se caler à côté.

![image1](https://cloud.githubusercontent.com/assets/10245123/7856758/e0822d94-052b-11e5-85e7-ff59f23b7888.png)

http://www.simply-ce.com/demo/page/7220-offres

**Comment by remijean** [comment]
@simplyce Bug corrigé et en attente de mise en production !
