### ISSUE TITLE
Urgent : Pas d'envoi d'emails sur les plateformes

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#34]
J'ai 2 administrateurs de CE différents (http://www.cetsa.fr/page/10488-actualites / http://www.ceideatransport.com/page/3985-actualites) qui me disent avoir fait des envois d'emails qu'aucun des salariés n'a reçu ??

Pouvez-vous regarder svp?

**Comment by sylfabre** [comment]
@simplyce Salut Malek. Je suis en train de voir avec Gandi pourquoi certaines de nos tâches planifiées ne se lancent plus toutes les heures depuis vendredi soir (dont celle qui envoie les emails). Du coup je lance manuellement le script régulièrement mais je ne suis pas aussi régulier qu'un ordinateur !

Je te préviens ici quand c'est revenu à la normale

**Comment by sylfabre** [comment]
@simplyce Bonne nouvelle, nos tâches automatiques tournent à nouveau ! Et donc les emails partent à nouveau

@PierreGrateau @ArnaudDLT pour info
