### ISSUE TITLE
Problème Compta Internet Explorer 10

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#35]
Dans IE 10, impossibilité de charger des factures dans les formulaires de saisie comptable. La barre de chargement se lance mais aucun fichier ne s'uploade réellement, même après plusieurs minutes d'attente.

La cliente ne peut utiliser d'autre navigateur (intranet de la société), et elle attend que je la prévienne lorsqu'une action aura été réalisée. Merci de me tenir informé et bon courage

**Comment by sylfabre** [comment]
@simplyce Il me manque des éléments pour essayer de reproduire le bug
- le document qu'elle tente d'enregistrer
- l'url de la page où se situe le problème

Merci !

**Comment by simplyce** [comment]
Salut Sylvain,
Ci-dessous l'URL
http://www.cegh.fr/comptabilite/saisie/ecriture/edition/58310 

Concernant le fichier, nous avons essayé ensemble avec plusieurs fichiers différents (pdf / jpeg / png) et aucun ne passait.

**Comment by sylfabre** [comment]
@simplyce Je viens de tester sous IE10 avec Windows 7 ça fonctionne.
Peux-tu m'indiquer la version de Windows utilisée stp ?
Si je n'arrive toujours pas à le reproduire, est-ce que je peux prendre contact avec la personne directement ?

**Comment by simplyce** [comment]
Je t'avoue que je suis incapable de te répondre.
Je te donne ses coordonnées, en espérant qu'elle sache elle-même !
Chantal MANNIELO
Tél.: 02.40.54.49.07
E-Mail: cmanniello@g-h.fr

**Comment by sylfabre** [comment]
@simplyce OK merci je prends contact avec elle demain

**Comment by sylfabre** [comment]
@simplyce J'ai pas eu le temps aujourd'hui, j'ai passé pas mal de temps à analyser des pistes données par Gandi pour chercher d'où vient le problème des emails qui ne partent plus. Je m'en occupe demain !

**Comment by sylfabre** [comment]
@simplyce Je n'ai pas réussi à l'avoir au téléphone, je lui ai envoyé un email avec mes coordonnées pour qu'elle revienne vers moi quand ça l'arrange

**Comment by sylfabre** [comment]
@simplyce Je viens de l'avoir au téléphone, elle m'a indiqué que son problème ne portait pas sur un téléchargement de fichier mais de retrait d'écritures comptables passées en double. J'ai transmis l'affaire à un collègue qui s'y connait davantage en compta.
