### ISSUE TITLE
Urgent : Problème de suivi de ventes

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#36]
L'utilitaire de suivi des ventes patauge dans la semoule, et n'affiche rien

![image](https://cloud.githubusercontent.com/assets/10245123/7978926/2035df70-0a9b-11e5-8ca5-4b82bda820ca.png)
http://www.simply-ce.com/demo/master/ventes

**Comment by sylfabre** [comment]
@simplyce C'est corrigé !

**Comment by simplyce** [comment]
@sylfabre je rencontre de nouveau le problème !

**Comment by sylfabre** [comment]
@simplyce Corrigé !
