### ISSUE TITLE
Urgent: Deconnexion des sites

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#37]
Bonjour,

Je n'arrive pas à me deconnecter des sites, si bien qu'un élu se log encore avec mes identifiants sur son pc. Merci de voir pour que je puisse transmettre l'info.
![image](https://cloud.githubusercontent.com/assets/10245123/8006174/91adf4fc-0b91-11e5-99d5-4c4ecc4b9319.png)

http://www.simply-ce.com/demo/membres/profil/92479

**Comment by sylfabre** [comment]
@simplyce ok je regarde

**Comment by sylfabre** [comment]
@simplyce Je viens de tester avec mon compte et je suis bien déconnecté.
Attention, quand tu te déconnectes, ça ne ferme que la session en cours, pas toutes les sessions. Est-ce que ça peut expliquer le problème ?
Je vais voir pour fermer toutes les sessions associées à ton compte

**Comment by simplyce** [comment]
C'est vraiment curieux, je n'arrivais pas à me déconnecter

**Comment by sylfabre** [comment]
@simplyce Je viens de développer une modification de la page de déconnexion : il est maintenant possible de supprimer l'ensemble des sessions ouvertes.
