### ISSUE TITLE
Urgent : Problème paiement par chèque

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#38]
Les paiements par chèque ne passent plus sur la plateforme, et ne sont pas retranscrits dans l'utilitaire de suivi des ventes. Pourtant, un mail est bien envoyé à la personne effectuant l'achat. ça me pose un gros souci, je ne sais pas depuis quand ça ne fonctionne plus et les gens attendent potentiellement des billets. Est-il possible de retracer les différentes demandes sur une ou deux semaines?

![image](https://cloud.githubusercontent.com/assets/10245123/8187707/9f8c88f4-1451-11e5-9445-3e57a62b635f.png)
http://www.simply-ce.com/demo-briochedoree/billetterie/offre/33363-v-parc-du-puy-du-fou

**Comment by sylfabre** [comment]
@simplyce C'est corrigé. Les ventes étaient bien enregistrées et apparaissent maintenant dans le backoffice.
