### ISSUE TITLE
Lien pour paramétrage des codes d'accès utilisateur

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#4]
Bonjour,
Problème déjà rencontré sur d'autres plateformes. Lors de l'inscription d'un utilisateur, le lien envoyé pour paramétrage du mot de passe ne fonctionne pas. 
![image](https://cloud.githubusercontent.com/assets/10245123/5755196/eae66d7e-9ca1-11e4-8a4b-e91d462e3d48.png)
http://www.simply-ce.com/demo-maludis/membres/connexion 
Il faudrait débloquer l'accès de Magali AMIOT.
Merci !

**Comment by sylfabre** [comment]
@simplyce Je suis dessus pour trouver la cause, mais a priori ce n'est pas la même chose que la dernière fois.

**Comment by sylfabre** [comment]
@simplyce Tu peux lui donner cette url : http://www.simply-ce.com/demo-maludis/membres/mot-de-passe/creer?once=1&timestamp=2015-01-15T09:36:16+00:00&userId=123013&signature=09f08af2542ada464b7b65f11bd05626ed9bb1b7109e4fb51ec2d06fcbb87c5c

A noter que les urls précédemment émises sont probablement erronées : en as-tu envoyées beaucoup ?

**Comment by simplyce** [comment]
Salut Sylvain,
Il y'a eu une 100aine de notification lundi pour le CE PLS, mais je n'ai pas eu de retour pour l'instant concernant un dysfonctionnement du paramétrage du mdp.
