### ISSUE TITLE
Bouton/Filtre "Avec subvention uniquement"

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#40]
Salut Sylvain,
Suite à nos échanges du jour sur le sujet, j'ai fait quelques tests sur la même plateforme. La subvention a été paramétrée sur les catégories "Sports / Bien-être" et je me retrouve en appliquant le filtre avec d'autres catégories comme le cinéma, les loisirs... offres sur lesquelles aucune subvention n'est applicable ni appliquée.

http://www.cecameleongroup.fr/page/12278-billetterie-locale

![image](https://cloud.githubusercontent.com/assets/10245123/8235327/9a79aec8-15e1-11e5-8485-182c79188dfa.png)

**Comment by sylfabre** [comment]
@simplyce C'est corrigé
