### ISSUE TITLE
Compte de Cantonnement

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#41]
http://www.simply-ce.com/demo/master/compte 
![image](https://cloud.githubusercontent.com/assets/10245123/8699384/700f4826-2b05-11e5-94a6-fd09214dd43f.png)

**Comment by sylfabre** [comment]
@simplyce Notre serveur chez Gandi a commencé à utiliser une nouvelle adresse IP qui n'était pas autorisée chez LemonWay qui refusait les connexions. Ils ont mis à jour de leur côté, ça marche à nouveau !
