### ISSUE TITLE
Problème affichage des images

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#42]
Bonjour,
Suite aux modifications apportées sur les images, tous les logos sur les plateformes de mes clients ont été tronqués ou ont disparu.
http://www.ceideatransport.com/membres/connexion
![image](https://cloud.githubusercontent.com/assets/10245123/8801375/69f8a630-2fba-11e5-87a6-ffb2f1c601aa.png)

**Comment by remijean** [comment]
@simplyce salut Malek, je m'en occupe asap!

**Comment by remijean** [comment]
@simplyce salut Malek, je viens de pusher un correctif, j'attend ton retour !
