### ISSUE TITLE
Admin Master / Organisation

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#46]
La recherche ne fonctionne pas et m'affiche l'erreur ci-dessous

http://www.simply-ce.com/demo-zb/master/organisations
![image](https://cloud.githubusercontent.com/assets/10245123/9356041/54009e3e-467e-11e5-903f-05445b76f29e.png)

**Comment by sylfabre** [comment]
@simplyce C'est corrigé
