### ISSUE TITLE
Admin Master : Accès impossible

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#47]
Je demande l'accès à l'admin master et je tombe sur un écran blanc...

https://www.simply-ce.com/demo/master/membres

![image](https://cloud.githubusercontent.com/assets/10245123/9574920/ba9d6a0e-4fcb-11e5-9776-7dbac9190881.png)

**Comment by sylfabre** [comment]
@simplyce Je regarde

**Comment by sylfabre** [comment]
@simplyce Je viens de changer quelque chose dans le code du site, est-ce que ça te le fait encore ?

**Comment by simplyce** [comment]
Pareil

**Comment by sylfabre** [comment]
@simplyce Pour info, j'ai trouvé la cause
