### ISSUE TITLE
Admin Master : Transactions

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#48]
Message d'erreur lorsque je tente de consulter les transcations.

![image](https://cloud.githubusercontent.com/assets/10245123/9575739/2fb52fce-4fd2-11e5-994a-829a00056c4a.png)
https://www.simply-ce.com/demo/master/ventes

**Comment by sylfabre** [comment]
@simplyce Le message s'affiche inopinément, c'est corrigé
