### ISSUE TITLE
Bug changement de thème du site

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#49]
Suite à un changement de thème, la plateforme n'est plus du tout accessible

https://www.simply-ce.com/demo-ab/public/common/static/500.php?uid=55e5b20e3ae23&mail=sav@simply-ce.com
![image](https://cloud.githubusercontent.com/assets/10245123/9606532/33b6a60a-50c4-11e5-9cb6-788988b39128.png)

**Comment by remijean** [comment]
@simplyce bug corrigé !
