### ISSUE TITLE
Non prise en compte de la subvention sur les options de prestation obligatoire

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#5]
Création d'une vente en ligne, type événement, avec une prestation obligatoire à 15€ et une option de cette même presta obligatoire à 10€. Mise en place d'une subvention de 30€ sur cette événement.

http://www.simply-ce.com/demomismo/billetterie/offre/36695-u-test-subventions-sur-options
![image](https://cloud.githubusercontent.com/assets/10245123/5758992/909ede18-9cca-11e4-88e0-93d2f7fa85ae.png)
1er pb : la ligne sous-test 1 s'affiche à -5€ (devrait être bloquée à 0)

Ensuite je participe à l'événement, en cochant la presta obligatoire et son option (soit 25€)
![image](https://cloud.githubusercontent.com/assets/10245123/5759021/d9607814-9cca-11e4-8910-d68c25275beb.png)
Le montant à payer s'affiche bien à 0€, au vu de la subvention.

Au moment du paiement, il me demande de payer 10€, car l'option n'a finalement pas été prise en compte.
![image](https://cloud.githubusercontent.com/assets/10245123/5759062/1ff7b8d2-9ccb-11e4-8b66-7d761707ab9f.png)

**Comment by sylfabre** [comment]
@simplyce Je regarde

**Comment by sylfabre** [comment]
@simplyce J'ai corrigé pour le -5€

@PierreGrateau C'est la demande inverse de https://github.com/sylfabre/buypacker-dev/issues/3779
Je te laisse revenir vers moi

**Comment by PierreGrateau** [comment]
@simplyce Est ce que la subvention doit s'appliquer aux options de livraison ?

**Comment by simplyce** [comment]
Oui

**Comment by PierreGrateau** [comment]
@sylfabre ok dans ce cas on peut faire ce que demande Malek

**Comment by sylfabre** [comment]
@PierreGrateau @simplyce Prévu pour la prochaine mise à jour
