### ISSUE TITLE
Urgent : Problème désactivation des catégories

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#50]
http://www.cennd.fr/page/7458-offres

![image](https://cloud.githubusercontent.com/assets/10245123/9690781/bc16ceae-533e-11e5-8846-c8f164289975.png)

J'ai désactivé les catégories bons d'achat sur la plateforme CE NND, elles n'apparaissent plus dans le bandeau de gauche mais les offres qui y sont rangées apparaissent dans la billetterie. Urgent et très problématique. Merci d'avance

**Comment by sylfabre** [comment]
@simplyce Je regarde

**Comment by sylfabre** [comment]
@simplyce Corrigé
