### ISSUE TITLE
Problème de connexion

### ISSUE THREAD

**Issue by sylfabre** [PierreGrateau/simplyce-dev#51]
@simplyce Hello Malek, Pierre me transmet le message suivant :
*Malek me dit qu'ils (contact@simply-ce.com et commercial@simply-ce.com) ont accès à l'admin master mais que quand ils essaient de se connecter sur d'autres sites que le site de démo, ils n'y arrivent pas. 
Peux tu voir avec lui stp ?*

Peux-tu m'en dire davantage stp
- quelle url / plateforme ?
- qu'est-ce qui bloque pour se connecter ?

**Comment by sylfabre** [comment]
@simplyce je viens de tester en me mettant admin site comme vous et j'arrive à me connecter.
Pourrais-tu me communiquer le mot de passe d'une des 2 comptes stp (quitte à le changer avant) pour que je puisse essayer ?

**Comment by sylfabre** [comment]
@simplyce Au passage tu peux répondre au mail reçu par GitHub ça affiche directement la réponse sur le site et je la reçois également

**Comment by simplyce** [comment]
commercial@simplyce.fr

sce03051985



*De :* Sylvain [mailto:notifications@github.com]
*Envoyé :* lundi 14 septembre 2015 17:17
*À :* PierreGrateau/simplyce-dev <simplyce-dev@noreply.github.com>
*Cc :* Simply CE <direction@simplyce.fr>
*Objet :* Re: [simplyce-dev] Problème de connexion (#51)



@simplyce <https://github.com/simplyce> je viens de tester en me mettant
admin site comme vous et j'arrive à me connecter.
Pourrais-tu me communiquer le mot de passe d'une des 2 comptes stp (quitte
à le changer avant) pour que je puisse essayer ?

—
Reply to this email directly or view it on GitHub
<https://github.com/PierreGrateau/simplyce-dev/issues/51#issuecomment-140113129>
.

**Comment by sylfabre** [comment]
http://www.ce-asc.fr/

**Comment by sylfabre** [comment]
@simplyce En fait je n'arrive à me connecter à aucun compte avec ce mot de passe et j'ai vérifié le code qui vérifie le mot de passe : "sce03051985" n'est pas le mot de passe associé à ce compte https://www.simply-ce.com/demo/membres/profil/148024?mode=admin

Je n'ai pas accès aux mots de passe du coup il faut le configurer à nouveau en indiquant mot de passe perdu sur la plateforme 3250 - Simply Ticket

**Comment by sylfabre** [comment]
@simplyce Je viens de test sur http://www.ce-asc.fr/ avec le compte de commercial@simplyce.fr et le mot de passe sce03051985 j'ai bien l'admin master ! On se fait un partage d'écran avec teamviewer ?
![image](https://cloud.githubusercontent.com/assets/3177556/9854767/c9bad87e-5b0a-11e5-8302-86559bfb97f4.png)

**Comment by simplyce** [comment]
Salut Sylvain,



Je viens de refaire des tests sur plusieurs plateformes et ça fonctionne à
présent ! Va savoir…



Je vais dire aux filles d’utiliser leurs codes à partir de demain et te
dirai si elles rencontrent un problème.



*De :* Sylvain [mailto:notifications@github.com]
*Envoyé :* lundi 14 septembre 2015 18:03
*À :* PierreGrateau/simplyce-dev <simplyce-dev@noreply.github.com>
*Cc :* Simply CE <direction@simplyce.fr>
*Objet :* Re: [simplyce-dev] Problème de connexion (#51)



@simplyce <https://github.com/simplyce> Je viens de test sur
http://www.ce-asc.fr/ avec le compte de commercial@simplyce.fr et le mot de
passe sce03051985 j'ai bien l'admin master ! On se fait un partage d'écran
avec teamviewer ?
[image: image]
<https://cloud.githubusercontent.com/assets/3177556/9854767/c9bad87e-5b0a-11e5-8302-86559bfb97f4.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/PierreGrateau/simplyce-dev/issues/51#issuecomment-140125574>
.
