### ISSUE TITLE
Urgent : Problème IFRAME

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#53]
Bonjour,

Lorsqu'on essaye d'ajouter une URL pour générer l'iframe, on a un message d'erreur et la frame ne se charge pas. Merci de regarder (démo importante demain matin !!)

Bon courage,

Malek

![image](https://cloud.githubusercontent.com/assets/10245123/10575381/3aba19f6-765c-11e5-90fe-cdd8481d514f.png)
http://www.simply-ce.com/demo-briochedoree/page/edition/12221

**Comment by sylfabre** [comment]
@simplyce Je viens d'essayer et ça fonctionne chez moi. Peux-tu me copier-coller l'url exacte que tu saisies stp ?

**Comment by simplyce** [comment]
Salut Sylvain,

J’ai essayé entre autres avec celle-ci
http://www.capprivileges.fr/

**Comment by sylfabre** [comment]
@simplyce Ca fonctionne aussi avec ça. On peut faire un partage d'écran dès que tu es dispo ?

**Comment by simplyce** [comment]
Ok, c’est bon right now



*De :* Sylvain [mailto:notifications@github.com]
*Envoyé :* lundi 19 octobre 2015 12:41
*À :* PierreGrateau/simplyce-dev <simplyce-dev@noreply.github.com>
*Cc :* Simply CE <direction@simplyce.fr>
*Objet :* Re: [simplyce-dev] Urgent : Problème IFRAME (#53)



@simplyce <https://github.com/simplyce> Ca fonctionne aussi avec ça. On
peut faire un partage d'écran dès que tu es dispo ?

—
Reply to this email directly or view it on GitHub
<https://github.com/PierreGrateau/simplyce-dev/issues/53#issuecomment-149180987>
.

**Comment by remijean** [comment]
@sylfabre lorsque le site de l'api pour checker les urls de l'iframe plante le bug surgit

**Comment by sylfabre** [comment]
@simplyce @remijean J'ai remplacé le système que l'on utilisait, le bug ne devrait plus se produire dès la prochaine mise en prod
