### ISSUE TITLE
URGENT : Admin Master / Transactions

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#54]
@sylfabre 
Salut Sylvain,
Toutes les ventes apparaissent dupliquées, curieux...
![image](https://cloud.githubusercontent.com/assets/10245123/11113542/12b753f4-891e-11e5-8d82-639b75cc0145.png)

https://www.simply-ce.com/demo/master/ventes

**Comment by sylfabre** [comment]
@simplyce Salut Malek, d'après les ids des ventes dans la 1ère colonne, il n'y a aucun doublon

**Comment by simplyce** [comment]
ok désolé ;)
