### ISSUE TITLE
Problème UX / Catégories de gauche

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#55]
Gros souci sur le bandeau de gauche !

https://www.simply-ce.com/demo/page/7220-offres
![image](https://cloud.githubusercontent.com/assets/10245123/11144177/230267ac-89fb-11e5-9ec4-77aae3d19b07.png)

**Comment by sylfabre** [comment]
@simplyce C'est corrigé, un test oublié par un collègue et qui s'est retrouvé en prod ...
