### ISSUE TITLE
Admin Master / Transactions

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#57]
Lorsque je clique sur l'oeil pour voir le détail des transactions, le système ne m'autorise pas l'accès...

![image](https://cloud.githubusercontent.com/assets/10245123/11211368/2f66d410-8d2f-11e5-9dc1-20634dce50bf.png)
http://www.ceideatransport.com/membres/connexion?redirect=%2Fmaster%2Fventes%2Ftransaction%2F228893

**Comment by simplyce** [comment]
Regarde plutot cet exemple, plus parlant...

http://www.cennd.fr/membres/sudo?redirect=%2Fmaster%2Fventes%2Ftransaction%2F227614
![image](https://cloud.githubusercontent.com/assets/10245123/11211437/c4ee9360-8d2f-11e5-80de-9c772563f05b.png)

**Comment by sylfabre** [comment]
@simplyce La 1ère copie d'écran indique que tu n'es pas connecté sur la plateforme d'IDEA, la seconde correspond à une page sécurisée où l'on te redemande ton mot de passe et où celui saisit n'est pas bon. Il n'y a pas de problème d'autorisation d'accès pour moi

**Comment by simplyce** [comment]
Sur l'écran 2 j'essaye de retaper mon mot de passe mais le système m'indique qu'il n'est pas bon... C'est pas faute d'avoir essayé...

**Comment by simplyce** [comment]
Autre problème, lié ou non à celui-ci, j'ai des clients de chez vous (un salarié Adefim, Bertrand PATIER) qui a commandé des places UGC national et ça n'apparait plus dans l'utilitaire. La dernière mise en prod a du changer qqs trucs...

**Comment by sylfabre** [comment]
@simplyce Petit rappel, est important de garder 1 problème par "issue" sur github ;-) Je le déplace

**Comment by sylfabre** [comment]
@simplyce J'ai rajouté sur la page de confirmation du mot de passe le compte connecté, peut-être que ça n'est pas le bon ? En tout cas j'ai essayé avec mon compte et mon mot de passe est accepté directement. Une autre piste : essayer de se déconnecter en allant sur http://www.cennd.fr/membres/deconnexion
