### ISSUE TITLE
Problème à l'annulation d'un achat

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#6]
@PierreGrateau : Suite à notre ct, j'ai essayé d'annuler l'achat et je tombe sur le message d'erreur ci-dessous 
![image](https://cloud.githubusercontent.com/assets/10245123/5778531/48aad044-9d9c-11e4-9301-15bcf63ea772.png)
http://www.cepls.fr/billetterie/participants/detail/275079

**Comment by sylfabre** [comment]
@simplyce La prochaine fois, peux-tu me copier coller l'identifiant de l'erreur qui est affiché stp ? Ca m'évite de le recopier lettre par lettre ! L'achat est noté comme annulé, je vais creuser pour voir si c'est bien le cas notamment au niveau de la subvention

**Comment by sylfabre** [comment]
@simplyce J'ai vérifié l'achat est bien annulé.
J'ai corrigé la cause du problème
