### ISSUE TITLE
URGENT : Création de plateforme

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#60]
J'ai rdv dans 50mn, j'essaye de créer une plateforme de démo et impossible. QQn peut m'aider !! 
![image](https://cloud.githubusercontent.com/assets/10245123/11929975/c26b7af2-a7df-11e5-956b-c86d6cf986e7.png)
https://www.simply-ce.com/demo/master/plateformes

**Comment by sylfabre** [comment]
@ArnaudDLT Même erreur avec BuyPacker\Vendor::getAccountingBankAccountId()

**Comment by ArnaudDLT** [comment]
@simplyce corrigé

**Comment by ArnaudDLT** [comment]
@simplyce lorsqu'il y a une telle urgence, n'hésitez pas à nous appeler pour qu'on puisse réagir immédiatement
