### ISSUE TITLE
Virement Wallet Simply Ticket 

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#61]
https://www.simply-ce.com/demo/master/compte

![image](https://cloud.githubusercontent.com/assets/10245123/12139519/536da768-b461-11e5-8697-8c02d1683d98.png)

**Comment by sylfabre** [comment]
@simplyce J'étais justement en train de regarder cette erreur, c'est parce que tu demandes un virement trop important. J'ai mis un seuil minimal de 150€ pour permettre de rembourser des utilisateurs bénéficiant d'une subvention importante. Le seuil était plus bas avant mais un cas s'est produit où l'on ne pouvait pas rembourser car il ne restait plus assez sur ton compte.

**Comment by simplyce** [comment]
J’ai ré essayé et ça ne fonctionne pas non plus pour 600€



*De :* Sylvain [mailto:notifications@github.com]
*Envoyé :* mercredi 6 janvier 2016 10:39
*À :* PierreGrateau/simplyce-dev <simplyce-dev@noreply.github.com>
*Cc :* Simply CE <direction@simplyce.fr>
*Objet :* Re: [simplyce-dev] Virement Wallet Simply Ticket (#61)



@simplyce <https://github.com/simplyce> J'étais justement en train de
regarder cette erreur, c'est parce que tu demandes un virement trop
important. J'ai mis un seuil minimal de 150€ pour permettre de rembourser
des utilisateurs bénéficiant d'une subvention importante. Le seuil était
plus bas avant mais un cas s'est produit où l'on ne pouvait pas rembourser
car il ne restait plus assez sur ton compte.

—
Reply to this email directly or view it on GitHub
<https://github.com/PierreGrateau/simplyce-dev/issues/61#issuecomment-169277436>
.

**Comment by sylfabre** [comment]
@simplyce C'est un problème de configuration de notre côté, je suis dessus

**Comment by sylfabre** [comment]
@simplyce J'ai oublié de mettre ton IBAN sur SMoney en fait

**Comment by sylfabre** [comment]
@simplyce C'est corrigé et je viens de déclencher un virement de 600€
