### ISSUE TITLE
Compta PLS

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#62]
http://www.cepls.fr/comptabilite/documents/compte-de-resultat/8630
![image](https://cloud.githubusercontent.com/assets/10245123/12291971/9d85761c-b9ea-11e5-9005-8707c43f2f11.png)

J'ai un souci, ça me retourne des données complètement foireuses...

**Comment by PierreGrateau** [comment]
@simplyce c'est à dire ? Peux tu nous dire ce qui est "foireux" ?

**Comment by simplyce** [comment]
Le compte de résultat affiché est complètement incohérent, et en regardant dans le grand livre je ne vois rien qui l'explique.

**Comment by simplyce** [comment]
Aussi, il paraitrait (selon le client) que des mouvements de son compte en ligne n'apparaissent pas dans son menu crédit et facturation...

**Comment by sylfabre** [comment]
@ArnaudDLT Je t'assigne le bug car a priori c'est de la compta.

@simplyce Afin de ne pas mélanger 2 sujets sur le même bug, pour le menu crédit et facturation peux-tu créer un autre bug en donnant davantage de détails stp ?

**Comment by ArnaudDLT** [comment]
@simplyce j'ai besoin de davantage de matière. Que signifie incohérent ? Pouvez-vous me donner un exemple sur un point particulier ?
