### ISSUE TITLE
Problème de visualisation des offres

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#7]
Il y'a un problème sur les offres du catalogue, qui ne peuvent être visualisées. Le problème a été détecté en navigant dans la catégorie "culture". 

![image](https://cloud.githubusercontent.com/assets/10245123/5779748/822fcb72-9da5-11e4-81a5-cf4cd12cc2e6.png)

http://www.simply-ce.com/demo/menu/2919

En cliquant sur l'une des offres, on tombe sur une page inexistante
![image](https://cloud.githubusercontent.com/assets/10245123/5779756/99a320ce-9da5-11e4-9b24-95bdb1d13d0e.png)
http://www.simply-ce.com/demo/billetterie/code-promo/36542-r-prieure-de-grammont

**Comment by sylfabre** [comment]
@simplyce C'est corrigé
