### ISSUE TITLE
Virement Ventes en ligne / Remboursement subventions créditées. 

### ISSUE THREAD

**Issue by simplyce** [PierreGrateau/simplyce-dev#8]
Demande de virement des fonds issus des ventes en ligne, erreur ci-dessous
![image](https://cloud.githubusercontent.com/assets/10245123/6128438/20b8cba6-b136-11e4-8be8-7c0d51734910.png)
http://www.cepls.fr/organisation/credit/8630 

J'aimerais également connaitre la procédure de remboursement de subventions créditées sur la plateforme?

Merci d'avance,

Malek

**Comment by sylfabre** [comment]
@simplyce Hello, Je viens de pusher sur le serveur un correctif.
Je transfère ta question à Arnaud.

Pour info, pour être sûr de ne pas passer à côté de quelque chose, il faut se forcer à ne traiter que d'un seul sujet sur un bug sur GitHub.

Bonne soirée

**Comment by sylfabre** [comment]
@ArnaudDLT Je te laisse revenir vers Malek pour sa question

**Comment by ArnaudDLT** [comment]
@simplyce nous allons rajouter un bouton pour demander un virement sur la page crédit et facturation. En attendant vous pouvez envoyer vos demandes à Sylvain.
@sylfabre le cdc est là : Dropbox/5bis. IT Past - 2come/Passé/Crédit et facturation
Slide 9

**Comment by ArnaudDLT** [comment]
@sylfabre j'ouvre un autre bug pour le manque de bouton
