### ISSUE TITLE
Manque bouton "Récupération du crédit"

### ISSUE THREAD

**Issue by ArnaudDLT** [PierreGrateau/simplyce-dev#9]
http://www.cepls.fr/organisation/credit/8630

Ajouter bouton "Demander un virement"
cf cdc Dropbox/5bis. IT Past - 2come/Passé/Crédit et facturation/
Slide 9

**Comment by sylfabre** [comment]
@simplyce Combien souhaitent-ils récupérer ?

**Comment by simplyce** [comment]
Salut Sylvain,

Il veulent un virement en retour de 4500€.

Merci d’avance,

Malek

De : Sylvain [mailto:notifications@github.com]
Envoyé : mercredi 11 février 2015 11:57
À : PierreGrateau/simplyce-dev
Cc : Malek TAZEROUT
Objet : Re: [simplyce-dev] Manque bouton "Récupération du crédit" (#9)


@simplyce<https://github.com/simplyce> Combien souhaitent-ils récupérer ?

**Comment by sylfabre** [comment]
@ArnaudDLT @PierreGrateau C'est bon de mon côté, vous pouvez procéder au virement sur LemonWay

**Comment by sylfabre** [comment]
@ArnaudDLT @PierreGrateau Pour info : https://trello.com/c/teJaquSo/669-subventions-retirer-du-credit-en-ligne
